import type {
  User,
  Facility,
  Patient,
  ClinicalCase,
  SyncLog,
  AuditEntry,
  Notification,
  ChartDataPoint,
} from '@/types'

export const mockUsers: User[] = [
  {
    id: 'usr-001',
    email: 'sarah.benali@medinsight.dz',
    name: 'Dr. Sarah Benali',
    role: 'doctor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    facility: 'fac-001',
    department: 'Cardiologie',
    phone: '+213 555 010 001',
    createdAt: '2024-01-15T08:00:00Z',
    lastLogin: '2026-07-11T09:30:00Z',
    isActive: true,
  },
  {
    id: 'usr-002',
    email: 'karim.mansouri@medinsight.dz',
    name: 'Dr. Karim Mansouri',
    role: 'doctor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karim',
    facility: 'fac-001',
    department: 'Neurologie',
    phone: '+213 555 010 002',
    createdAt: '2024-02-20T10:00:00Z',
    lastLogin: '2026-07-10T14:15:00Z',
    isActive: true,
  },
  {
    id: 'usr-003',
    email: 'amina.touati@medinsight.dz',
    name: 'Infirmière Amina Touati',
    role: 'nurse',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amina',
    facility: 'fac-002',
    department: 'Urgences',
    phone: '+213 555 010 003',
    createdAt: '2024-03-10T07:30:00Z',
    lastLogin: '2026-07-11T06:45:00Z',
    isActive: true,
  },
  {
    id: 'usr-004',
    email: 'mohamed.cherif@medinsight.dz',
    name: 'Mohamed Cherif',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mohamed',
    facility: 'fac-001',
    department: 'Administration',
    phone: '+213 555 010 004',
    createdAt: '2023-11-01T09:00:00Z',
    lastLogin: '2026-07-11T11:00:00Z',
    isActive: true,
  },
  {
    id: 'usr-005',
    email: 'nadia.bouzid@medinsight.dz',
    name: 'Dr. Nadia Bouzid',
    role: 'researcher',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nadia',
    facility: 'fac-003',
    department: 'Recherche Clinique',
    phone: '+213 555 010 005',
    createdAt: '2024-04-05T08:45:00Z',
    lastLogin: '2026-07-09T16:20:00Z',
    isActive: true,
  },
  {
    id: 'usr-006',
    email: 'youcef.hadj@medinsight.dz',
    name: 'Youcef Hadj',
    role: 'viewer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=youcef',
    facility: 'fac-004',
    department: 'Direction',
    phone: '+213 555 010 006',
    createdAt: '2024-05-12T12:00:00Z',
    lastLogin: '2026-07-08T10:30:00Z',
    isActive: true,
  },
  {
    id: 'usr-007',
    email: 'fatima.khelifi@medinsight.dz',
    name: 'Infirmière Fatima Khelifi',
    role: 'nurse',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima',
    facility: 'fac-005',
    department: 'Pédiatrie',
    phone: '+213 555 010 007',
    createdAt: '2024-06-18T07:00:00Z',
    lastLogin: '2026-07-11T08:00:00Z',
    isActive: true,
  },
  {
    id: 'usr-008',
    email: 'amine.slimani@medinsight.dz',
    name: 'Dr. Amine Slimani',
    role: 'doctor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amine',
    facility: 'fac-002',
    department: 'Chirurgie Orthopédique',
    phone: '+213 555 010 008',
    createdAt: '2024-07-22T09:15:00Z',
    lastLogin: '2026-07-11T13:45:00Z',
    isActive: true,
  },
]

export const mockFacilities: Facility[] = [
  {
    id: 'fac-001',
    name: 'CHU Mustapha',
    type: 'hospital',
    address: '1, Place Lieutenant Turki',
    city: 'Alger',
    country: 'Algérie',
    phone: '+213 21 50 00 00',
    email: 'contact@chumustapha.dz',
    bedCount: 2200,
    departmentCount: 35,
    staffCount: 4500,
    isActive: true,
    createdAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'fac-002',
    name: 'Hôpital Bab El Oued',
    type: 'hospital',
    address: '45, Rue de Tripoli',
    city: 'Alger',
    country: 'Algérie',
    phone: '+213 21 80 00 00',
    email: 'contact@hopbab-el-oued.dz',
    bedCount: 800,
    departmentCount: 18,
    staffCount: 1500,
    isActive: true,
    createdAt: '2023-02-15T00:00:00Z',
  },
  {
    id: 'fac-003',
    name: 'Clinique El Fath',
    type: 'clinic',
    address: '22, Rue des Frères Abbas',
    city: 'Alger',
    country: 'Algérie',
    phone: '+213 21 90 00 00',
    email: 'info@cliniquefath.dz',
    bedCount: 120,
    departmentCount: 8,
    staffCount: 250,
    isActive: true,
    createdAt: '2023-03-20T00:00:00Z',
  },
  {
    id: 'fac-004',
    name: 'Hôpital Parnet',
    type: 'hospital',
    address: '10, Route de Zeralda',
    city: 'Alger',
    country: 'Algérie',
    phone: '+213 21 40 00 00',
    email: 'contact@hop-parnet.dz',
    bedCount: 600,
    departmentCount: 14,
    staffCount: 1100,
    isActive: true,
    createdAt: '2023-04-10T00:00:00Z',
  },
  {
    id: 'fac-005',
    name: 'Centre Médical Hydra',
    type: 'laboratory',
    address: '7, Rue Amirouche',
    city: 'Alger',
    country: 'Algérie',
    phone: '+213 21 60 00 00',
    email: 'contact@cm-hydra.dz',
    bedCount: 30,
    departmentCount: 5,
    staffCount: 80,
    isActive: true,
    createdAt: '2023-05-05T00:00:00Z',
  },
]

export const mockPatients: Patient[] = [
  {
    id: 'pat-001',
    firstName: 'Aïcha',
    lastName: 'Boudiaf',
    dateOfBirth: '1958-03-12',
    gender: 'F',
    phone: '+213 555 100 001',
    address: '15, Rue Didouche Mourad, Alger',
    bloodType: 'A+',
    allergies: ['Pénicilline', 'Arachides'],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1001',
    isActive: true,
    createdAt: '2024-01-20T08:00:00Z',
    lastVisit: '2026-06-15T10:30:00Z',
  },
  {
    id: 'pat-002',
    firstName: 'Rachid',
    lastName: 'Mebarki',
    dateOfBirth: '1975-09-28',
    gender: 'M',
    phone: '+213 555 100 002',
    address: '8, Boulevard Krim Belkacem, Oran',
    bloodType: 'O+',
    allergies: ['Iode'],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1002',
    isActive: true,
    createdAt: '2024-02-14T09:30:00Z',
    lastVisit: '2026-07-01T14:00:00Z',
  },
  {
    id: 'pat-003',
    firstName: 'Lydia',
    lastName: 'Zeroual',
    dateOfBirth: '1982-06-15',
    gender: 'F',
    phone: '+213 555 100 003',
    address: '23, Rue Abane Ramdane, Constantine',
    bloodType: 'B-',
    allergies: ['Aspirine', 'Latex'],
    facilityId: 'fac-002',
    medicalRecordNumber: 'MRN-1003',
    isActive: true,
    createdAt: '2024-03-01T07:15:00Z',
    lastVisit: '2026-05-20T11:00:00Z',
  },
  {
    id: 'pat-004',
    firstName: 'Omar',
    lastName: 'Taleb',
    dateOfBirth: '1965-11-03',
    gender: 'M',
    phone: '+213 555 100 004',
    address: '4, Avenue Colonel Amirouche, Blida',
    bloodType: 'AB+',
    allergies: [],
    facilityId: 'fac-003',
    medicalRecordNumber: 'MRN-1004',
    isActive: true,
    createdAt: '2024-03-18T10:00:00Z',
    lastVisit: '2026-07-05T09:00:00Z',
  },
  {
    id: 'pat-005',
    firstName: 'Souad',
    lastName: 'Benmalek',
    dateOfBirth: '1990-01-22',
    gender: 'F',
    phone: '+213 555 100 005',
    address: '31, Rue Larbi Ben M\'hidi, Tizi Ouzou',
    bloodType: 'O-',
    allergies: ['Sulfamides'],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1005',
    isActive: true,
    createdAt: '2024-04-05T08:45:00Z',
    lastVisit: '2026-06-28T15:30:00Z',
  },
  {
    id: 'pat-006',
    firstName: 'Djamel',
    lastName: 'Kharchi',
    dateOfBirth: '1952-07-09',
    gender: 'M',
    phone: '+213 555 100 006',
    address: '12, Rue des Martyrs, Annaba',
    bloodType: 'A-',
    allergies: ['Morphine', 'Pollens'],
    facilityId: 'fac-004',
    medicalRecordNumber: 'MRN-1006',
    isActive: true,
    createdAt: '2024-04-22T11:30:00Z',
    lastVisit: '2026-07-08T08:15:00Z',
  },
  {
    id: 'pat-007',
    firstName: 'Meriem',
    lastName: 'Ait Ahmed',
    dateOfBirth: '1988-04-17',
    gender: 'F',
    phone: '+213 555 100 007',
    address: '7, Rue Hassiba Ben Bouali, Chlef',
    bloodType: 'B+',
    allergies: ['Produits laitiers'],
    facilityId: 'fac-005',
    medicalRecordNumber: 'MRN-1007',
    isActive: true,
    createdAt: '2024-05-10T09:00:00Z',
    lastVisit: '2026-06-10T13:00:00Z',
  },
  {
    id: 'pat-008',
    firstName: 'Samir',
    lastName: 'Boucherit',
    dateOfBirth: '1971-12-01',
    gender: 'M',
    phone: '+213 555 100 008',
    address: '19, Boulevard Emir Abdelkader, Batna',
    bloodType: 'O+',
    allergies: [],
    facilityId: 'fac-002',
    medicalRecordNumber: 'MRN-1008',
    isActive: true,
    createdAt: '2024-05-28T07:30:00Z',
    lastVisit: '2026-07-10T10:45:00Z',
  },
  {
    id: 'pat-009',
    firstName: 'Dalila',
    lastName: 'Mansouri',
    dateOfBirth: '1963-08-25',
    gender: 'F',
    phone: '+213 555 100 009',
    address: '5, Rue Ahmed Bey, Setif',
    bloodType: 'A+',
    allergies: ['Cacahuètes', 'Poussière'],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1009',
    isActive: true,
    createdAt: '2024-06-15T10:15:00Z',
    lastVisit: '2026-06-22T09:30:00Z',
  },
  {
    id: 'pat-010',
    firstName: 'Farid',
    lastName: 'Guermazi',
    dateOfBirth: '1995-02-14',
    gender: 'M',
    phone: '+213 555 100 010',
    address: '28, Rue Colonel Lotfi, Tlemcen',
    bloodType: 'AB-',
    allergies: ['Ibuprofène'],
    facilityId: 'fac-003',
    medicalRecordNumber: 'MRN-1010',
    isActive: true,
    createdAt: '2024-07-01T08:00:00Z',
    lastVisit: '2026-07-03T14:15:00Z',
  },
  {
    id: 'pat-011',
    firstName: 'Naima',
    lastName: 'Charef',
    dateOfBirth: '1980-05-30',
    gender: 'F',
    phone: '+213 555 100 011',
    address: '3, Rue Abderrahmane Mira, Bejaia',
    bloodType: 'O+',
    allergies: ['Codeïne'],
    facilityId: 'fac-004',
    medicalRecordNumber: 'MRN-1011',
    isActive: true,
    createdAt: '2024-07-18T09:45:00Z',
    lastVisit: '2026-06-30T11:30:00Z',
  },
  {
    id: 'pat-012',
    firstName: 'Abdelkader',
    lastName: 'Rebiai',
    dateOfBirth: '1956-10-08',
    gender: 'M',
    phone: '+213 555 100 012',
    address: '14, Avenue Ahmed Grir, Mostaganem',
    bloodType: 'B+',
    allergies: ['Pénicilline', 'Codéine'],
    facilityId: 'fac-005',
    medicalRecordNumber: 'MRN-1012',
    isActive: true,
    createdAt: '2024-08-05T07:00:00Z',
    lastVisit: '2026-07-09T16:00:00Z',
  },
  {
    id: 'pat-013',
    firstName: 'Sabrina',
    lastName: 'Djaballah',
    dateOfBirth: '1998-12-20',
    gender: 'F',
    phone: '+213 555 100 013',
    address: '9, Rue Ahmed Ouldghezouel, Djelfa',
    bloodType: 'A+',
    allergies: [],
    facilityId: 'fac-001',
    medicalRecordNumber: 'MRN-1013',
    isActive: true,
    createdAt: '2024-08-22T11:00:00Z',
    lastVisit: '2026-07-11T08:30:00Z',
  },
  {
    id: 'pat-014',
    firstName: 'Khaled',
    lastName: 'Ouali',
    dateOfBirth: '1970-06-05',
    gender: 'M',
    phone: '+213 555 100 014',
    address: '21, Boulevard Emir Abdelkader, Skikda',
    bloodType: 'O-',
    allergies: ['Aspirine', 'Poussière'],
    facilityId: 'fac-002',
    medicalRecordNumber: 'MRN-1014',
    isActive: true,
    createdAt: '2024-09-10T08:30:00Z',
    lastVisit: '2026-06-25T10:00:00Z',
  },
  {
    id: 'pat-015',
    firstName: 'Wassila',
    lastName: 'Ferhat',
    dateOfBirth: '1985-03-18',
    gender: 'F',
    phone: '+213 555 100 015',
    address: '6, Rue Abane Ramdane, Ghardaia',
    bloodType: 'AB+',
    allergies: ['Iode', 'Latex'],
    facilityId: 'fac-003',
    medicalRecordNumber: 'MRN-1015',
    isActive: true,
    createdAt: '2024-09-28T09:15:00Z',
    lastVisit: '2026-07-06T13:45:00Z',
  },
]

export const mockClinicalCases: ClinicalCase[] = [
  {
    id: 'cas-001',
    title: 'Fracture du fémur gauche',
    description: 'Patient présentant une fracture comminutive du tiers moyen du fémur gauche suite à une chute.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-002',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Fracture comminutive du fémur gauche',
    symptoms: ['Douleur intense', 'Impossibilité de marcher', 'Œdème', 'Déformation du membre'],
    treatment: 'Réduction chirurgicale et pose de plaque ostéosynthétique',
    tags: ['Orthopédie', 'Chirurgie', 'Urgence'],
    createdAt: '2026-07-01T08:30:00Z',
    updatedAt: '2026-07-05T14:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-002',
    title: 'Pneumonie bilatérale sévère',
    description: 'Pneumonie bilatérale avec détresse respiratoire nécessitant une hospitalisation en réanimation.',
    status: 'in_review',
    priority: 'critical',
    patientId: 'pat-006',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Pneumonie bilatérale à pneumocoque',
    symptoms: ['Fièvre 39.5°C', 'Toux productive', 'Dyspnée', 'Douleur thoracique', 'SpO2 88%'],
    treatment: 'Antibiothérapie IV (Amoxicilline-acide clavulanique), oxygénothérapie',
    tags: ['Pneumologie', 'Réanimation', 'Infection'],
    createdAt: '2026-06-28T02:15:00Z',
    updatedAt: '2026-07-06T09:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-003',
    title: 'Appendicite aiguë',
    description: 'Appendicite aiguë non compliquée, prise en charge chirurgicale en urgence.',
    status: 'resolved',
    priority: 'high',
    patientId: 'pat-010',
    facilityId: 'fac-003',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Appendicite aiguë',
    symptoms: ['Douleur fosse iliaque droite', 'Nausée', 'Vomissement', 'Fièvre 38.2°C'],
    treatment: 'Appendicectomie cœlioscopique',
    tags: ['Chirurgie Digestive', 'Urgence', 'Cœlioscopie'],
    createdAt: '2026-06-20T16:00:00Z',
    updatedAt: '2026-06-22T10:00:00Z',
    resolvedAt: '2026-06-22T10:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-004',
    title: 'Diabète de type 2 mal contrôlé',
    description: 'Patient diabétique avec HbA1c à 10.2%, nécessitant un ajustement thérapeutique.',
    status: 'active',
    priority: 'medium',
    patientId: 'pat-009',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Diabète de type 2 déséquilibré',
    symptoms: ['Polyurie', 'Polydipsie', 'Perte de poids', 'Fatigue', 'HbA1c 10.2%'],
    treatment: 'Metformine 1000mg x2, Gliclazide 80mg, insulinoterapie envisagée',
    tags: ['Endocrinologie', 'Chronique', 'Diabète'],
    createdAt: '2026-06-15T11:00:00Z',
    updatedAt: '2026-07-08T15:30:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-005',
    title: 'Infarctus du myocarde antérieur',
    description: 'IDMA avec sus-décalage du segment ST, prise en charge en cathlab en urgence.',
    status: 'in_review',
    priority: 'critical',
    patientId: 'pat-001',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Infarctus aigu du myocarde antérieur avec sus-décalage du ST',
    symptoms: ['Douleur thoracique compressive', 'Sueurs', 'Nausée', 'Irradiation bras gauche', 'Sus-décalage ST V1-V4'],
    treatment: 'Angioplastie primaire avec pose de stent, Double antiagrégation plaquettaire',
    tags: ['Cardiologie', 'Urgence', 'Cathlab'],
    createdAt: '2026-07-10T06:00:00Z',
    updatedAt: '2026-07-10T12:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-006',
    title: 'Asthme bronchique sévère',
    description: 'Exacerbation sévère d\'asthme bronchique avec statut asthmatique.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-005',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-002',
    diagnosis: 'Exacerbation sévère d\'asthme bronchique',
    symptoms: ['Dyspnée sévère', 'Sifflements', 'Toux nocturne', 'SpO2 91%', 'Utilisation muscles accessoires'],
    treatment: 'Nébulisation Salbutamol + Ipratropium, Corticothérapie IV, Surveillance SpO2',
    tags: ['Pneumologie', 'Urgence', 'Respiratoire'],
    createdAt: '2026-07-09T22:00:00Z',
    updatedAt: '2026-07-11T08:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-007',
    title: 'AVC ischémique territorial sylvien gauche',
    description: 'Accident vasculaire cérébral ischémique du territoire sylvien gauche avec hémiplégie droite.',
    status: 'active',
    priority: 'critical',
    patientId: 'pat-006',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-002',
    diagnosis: 'AVC ischémique du territoire sylvien gauche',
    symptoms: ['Hémiplégie droite', 'Aphasie', 'Déviation conjuguée', 'NIHSS 16'],
    treatment: 'Thrombolyse IV (alteplase), antiagrégation plaquettaire, kinésithérapie',
    tags: ['Neurologie', 'Urgence', 'AVC'],
    createdAt: '2026-07-08T14:30:00Z',
    updatedAt: '2026-07-11T10:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-008',
    title: 'Infection urinaire haute',
    description: 'Pyélonéphrite aiguë droite avec fièvre et douleur lombaire.',
    status: 'resolved',
    priority: 'medium',
    patientId: 'pat-003',
    facilityId: 'fac-005',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Pyélonéphrite aiguë droite',
    symptoms: ['Fièvre 39.8°C', 'Douleur lombaire droite', 'POLLakiurie', 'Hématurie'],
    treatment: 'Ciprofloxacine 500mg x2 pendant 14 jours, hydratation',
    tags: ['Urologie', 'Infection', 'Antibiothérapie'],
    createdAt: '2026-06-25T09:00:00Z',
    updatedAt: '2026-07-03T11:00:00Z',
    resolvedAt: '2026-07-03T11:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-009',
    title: 'Traumatisme crânien modéré',
    description: 'Traumatisme crânien après accident de la voie publique, GCS 13, scanner cérébral normal.',
    status: 'in_review',
    priority: 'high',
    patientId: 'pat-008',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-002',
    diagnosis: 'Traumatisme crânien modéré sans lésion intracrânienne',
    symptoms: ['Perte de connaissance brève', 'Céphalée', 'Nausée', 'GCS 13'],
    treatment: 'Surveillance neurologique, antalgiques, repos',
    tags: ['Neurologie', 'Traumatisme', 'Surveillance'],
    createdAt: '2026-07-07T20:00:00Z',
    updatedAt: '2026-07-10T08:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-010',
    title: 'Insuffisance cardiaque décompensée',
    description: 'Décompensation d\'insuffisance cardiaque gauche avec œdème pulmonaire.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-012',
    facilityId: 'fac-004',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Insuffisance cardiaque gauche décompensée FC 35%',
    symptoms: ['Dyspnée de décubitus', 'Œdème des membres inférieurs', 'Orthopnée', 'Crackles pulmonaires'],
    treatment: 'Furosémide IV, Nitroglycérine, Spironolactone, Bêtabloquant',
    tags: ['Cardiologie', 'Réanimation', 'Chronique'],
    createdAt: '2026-07-05T18:00:00Z',
    updatedAt: '2026-07-11T07:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-011',
    title: 'Cholangite aiguë',
    description: 'Cholangite aiguë sur lithiase cholédoquienne, triade de Charcot.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-004',
    facilityId: 'fac-003',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Cholangite aiguë sur lithiase biliaire',
    symptoms: ['Fièvre 40°C', 'Ictère', 'Douleur hypochondre droit', 'Frissons'],
    treatment: 'Antibiothérapie IV, CPRE en urgence, cholécystectomie programmée',
    tags: ['Chirurgie Digestive', 'Hépatologie', 'Urgence'],
    createdAt: '2026-07-09T10:00:00Z',
    updatedAt: '2026-07-11T09:30:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-012',
    title: 'Grossesse extra-utérine',
    description: 'Grossesse extra-utérine rompue avec hématopéritoine, prise en charge chirurgicale urgente.',
    status: 'resolved',
    priority: 'critical',
    patientId: 'pat-015',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Grossesse extra-utérine tubaire rompue',
    symptoms: ['Douleur pelvienne aiguë', 'Métrorragies', 'Syncope', 'Pâleur', 'Aménorrhée 8 semaines'],
    treatment: 'Salpingectomie urgente par coelioscopie, transfusion sanguine',
    tags: ['Gynécologie', 'Urgence', 'Chirurgie'],
    createdAt: '2026-06-18T03:00:00Z',
    updatedAt: '2026-06-18T08:00:00Z',
    resolvedAt: '2026-06-18T08:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-013',
    title: 'Insuffisance rénale chronique stade 4',
    description: 'Dégradation de la fonction rénale avec DFG à 22 ml/min, préparation à la dialyse.',
    status: 'active',
    priority: 'medium',
    patientId: 'pat-014',
    facilityId: 'fac-005',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Insuffisance rénale chronique stade 4',
    symptoms: ['Œdème', 'Fatigue', 'Anorexie', 'DFG 22 ml/min', 'Créatinine 4.8 mg/dl'],
    treatment: 'Régime hyposodé, EPO, fer, préparation fistule artério-veineuse',
    tags: ['Néphrologie', 'Chronique', 'Dialyse'],
    createdAt: '2026-05-10T14:00:00Z',
    updatedAt: '2026-07-05T11:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-014',
    title: 'Polytraumatisme routier',
    description: 'Polytraumatisme après accident de voiture: fracture du bassin, pneumothorax, hépatoplasie.',
    status: 'in_review',
    priority: 'critical',
    patientId: 'pat-011',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Polytraumatisme: fracture bassin, pneumothorax droit, plaie hépatique grade II',
    symptoms: ['Hémorragie', 'Détresse respiratoire', 'Instabilité hémodynamique', 'Douleur pelvienne'],
    treatment: 'Drain thoracique, embolisation hépatique, ostéosynthèse du bassin',
    tags: ['Traumatologie', 'Réanimation', 'Chirurgie'],
    createdAt: '2026-07-11T01:00:00Z',
    updatedAt: '2026-07-11T12:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-015',
    title: 'Crisis hypertensive',
    description: 'Crise hypertensive sévère avec ATCD d\'HTA non traitée, pression 220/130 mmHg.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-009',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Crise hypertensive sévère',
    symptoms: ['PA 220/130 mmHg', 'Céphalée occipitale', 'Troubles visuels', 'Nausée'],
    treatment: 'Nicardipine IV, Catapressan per os, surveillance PA continue',
    tags: ['Cardiologie', 'Urgence', 'Hypertension'],
    createdAt: '2026-07-10T15:00:00Z',
    updatedAt: '2026-07-11T10:30:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-016',
    title: 'Dépression majeure récurrente',
    description: 'Épisode dépressif majeur récidivant avec idées noires, échec du 2ème traitement antidépresseur.',
    status: 'draft',
    priority: 'medium',
    patientId: 'pat-007',
    facilityId: 'fac-005',
    assignedDoctorId: 'usr-002',
    diagnosis: 'Trouble dépressif majeur récurrente sévérité sévère',
    symptoms: ['Tristesse permanente', 'Insomnie', 'Anorexie', 'Idées noires', 'Apathie'],
    treatment: 'Escitalopram 20mg, TCC envisagées, évaluation du risque suicidaire',
    tags: ['Psychiatrie', 'Chronique', 'Suivi'],
    createdAt: '2026-07-08T10:00:00Z',
    updatedAt: '2026-07-08T10:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-017',
    title: 'Cancer du sein gauche stade IIB',
    description: 'Carcinome canalaire infiltrant du sein gauche, T2N1M0, prise en charge en oncologie.',
    status: 'active',
    priority: 'high',
    patientId: 'pat-013',
    facilityId: 'fac-001',
    assignedDoctorId: 'usr-005',
    diagnosis: 'Carcinome canalaire infiltrant du sein gauche T2N1M0',
    symptoms: ['Masse palpable 3cm', 'Adénopathie axillaire', 'Retraction cutanée'],
    treatment: 'Chimiothérapie néoadjuvante (FEC), chirurgie mastectomie, radiothérapie',
    tags: ['Oncologie', 'Chimiothérapie', 'Suivi'],
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-07-09T14:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-018',
    title: 'Lithiase rénale symptomatique',
    description: 'Calcoli rénaux multiples du rein droit avec colique néphrétique.',
    status: 'resolved',
    priority: 'medium',
    patientId: 'pat-005',
    facilityId: 'fac-003',
    assignedDoctorId: 'usr-008',
    diagnosis: 'Lithiase rénale bilatérale symptomatique',
    symptoms: ['Colique néphrétique', 'Hématurie', 'Nausée', 'Douleur lombaire'],
    treatment: 'Litotritie extracorporelle, drainage urétéral, régime hydrique',
    tags: ['Urologie', 'Chirurgie', 'Lithiase'],
    createdAt: '2026-06-22T21:00:00Z',
    updatedAt: '2026-07-02T10:00:00Z',
    resolvedAt: '2026-07-02T10:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-019',
    title: 'Intoxication médicamenteuse',
    description: 'Ingestion volontaire de Benzodiazépines, prise en charge en toxicologie.',
    status: 'draft',
    priority: 'high',
    patientId: 'pat-011',
    facilityId: 'fac-002',
    assignedDoctorId: 'usr-002',
    diagnosis: 'Intoxication aiguë par Benzodiazépines',
    symptoms: ['Somnolence', 'Désorientation', 'Hypotension', 'Dépression respiratoire'],
    treatment: 'Flumazénil, surveillance Continue, support psychiatrique',
    tags: ['Toxicologie', 'Urgence', 'Psychiatrie'],
    createdAt: '2026-07-11T04:00:00Z',
    updatedAt: '2026-07-11T04:00:00Z',
    attachments: [],
    notes: [],
  },
  {
    id: 'cas-020',
    title: 'Rhumatisme inflammatoire',
    description: 'Poussée de rhumatisme psoriasique avec atteinte des articulations interphalangiennes.',
    status: 'archived',
    priority: 'low',
    patientId: 'pat-004',
    facilityId: 'fac-004',
    assignedDoctorId: 'usr-001',
    diagnosis: 'Rhuate psoriasique - poussée articulaire',
    symptoms: ['Douleur articulaire', 'Raideur matinale', 'Swelling doigts', 'Dactylite'],
    treatment: 'Méthotrexate 15mg/semaine, AINS, corticoïdes locaux',
    tags: ['Rhumatologie', 'Chronique', 'Auto-immun'],
    createdAt: '2025-11-15T09:00:00Z',
    updatedAt: '2026-03-20T11:00:00Z',
    resolvedAt: '2026-03-20T11:00:00Z',
    attachments: [],
    notes: [],
  },
]

export const mockSyncLogs: SyncLog[] = [
  {
    id: 'sync-001',
    entityType: 'ClinicalCase',
    entityId: 'cas-001',
    action: 'create',
    status: 'synced',
    timestamp: '2026-07-01T08:30:00Z',
  },
  {
    id: 'sync-002',
    entityType: 'ClinicalCase',
    entityId: 'cas-002',
    action: 'create',
    status: 'synced',
    timestamp: '2026-06-28T02:15:00Z',
  },
  {
    id: 'sync-003',
    entityType: 'ClinicalCase',
    entityId: 'cas-005',
    action: 'update',
    status: 'pending',
    timestamp: '2026-07-10T12:00:00Z',
  },
  {
    id: 'sync-004',
    entityType: 'Patient',
    entityId: 'pat-013',
    action: 'update',
    status: 'synced',
    timestamp: '2026-07-11T08:30:00Z',
  },
  {
    id: 'sync-005',
    entityType: 'ClinicalCase',
    entityId: 'cas-014',
    action: 'create',
    status: 'failed',
    timestamp: '2026-07-11T01:05:00Z',
    errorMessage: 'Erreur de connexion au serveur de synchronisation',
  },
  {
    id: 'sync-006',
    entityType: 'AuditEntry',
    entityId: 'aud-001',
    action: 'create',
    status: 'synced',
    timestamp: '2026-07-11T09:30:00Z',
  },
  {
    id: 'sync-007',
    entityType: 'ClinicalCase',
    entityId: 'cas-007',
    action: 'update',
    status: 'pending',
    timestamp: '2026-07-11T10:00:00Z',
  },
  {
    id: 'sync-008',
    entityType: 'Patient',
    entityId: 'pat-008',
    action: 'create',
    status: 'synced',
    timestamp: '2026-07-10T10:45:00Z',
  },
  {
    id: 'sync-009',
    entityType: 'ClinicalCase',
    entityId: 'cas-015',
    action: 'update',
    status: 'failed',
    timestamp: '2026-07-11T10:35:00Z',
    errorMessage: 'Conflit de version détecté',
  },
  {
    id: 'sync-010',
    entityType: 'ClinicalCase',
    entityId: 'cas-004',
    action: 'update',
    status: 'synced',
    timestamp: '2026-07-08T15:30:00Z',
  },
]

export const mockAuditEntries: AuditEntry[] = [
  {
    id: 'aud-001',
    userId: 'usr-001',
    action: 'Consultation dossier',
    entity: 'Patient',
    entityId: 'pat-001',
    details: 'Consultation du dossier médical de Aïcha Boudiaf',
    ipAddress: '192.168.1.10',
    timestamp: '2026-07-11T09:30:00Z',
  },
  {
    id: 'aud-002',
    userId: 'usr-001',
    action: 'Modification traitement',
    entity: 'ClinicalCase',
    entityId: 'cas-004',
    details: 'Ajout de Gliclazide 80mg au protocole de traitement du Diabète de type 2',
    ipAddress: '192.168.1.10',
    timestamp: '2026-07-08T15:30:00Z',
  },
  {
    id: 'aud-003',
    userId: 'usr-008',
    action: 'Création cas clinique',
    entity: 'ClinicalCase',
    entityId: 'cas-001',
    details: 'Création du cas clinique "Fracture du fémur gauche"',
    ipAddress: '192.168.1.22',
    timestamp: '2026-07-01T08:30:00Z',
  },
  {
    id: 'aud-004',
    userId: 'usr-004',
    action: 'Accès aux statistiques',
    entity: 'Dashboard',
    entityId: 'dashboard-001',
    details: 'Consultation du tableau de bord administrateur',
    ipAddress: '192.168.1.5',
    timestamp: '2026-07-11T11:00:00Z',
  },
  {
    id: 'aud-005',
    userId: 'usr-002',
    action: 'Ajout note clinique',
    entity: 'ClinicalCase',
    entityId: 'cas-007',
    details: 'Ajout d\'une note de suivi neurologique pour le cas AVC',
    ipAddress: '192.168.1.15',
    timestamp: '2026-07-10T08:00:00Z',
  },
  {
    id: 'aud-006',
    userId: 'usr-003',
    action: 'Consultation dossier',
    entity: 'Patient',
    entityId: 'pat-006',
    details: 'Consultation du dossier médical de Djamel Kharchi',
    ipAddress: '192.168.1.30',
    timestamp: '2026-07-08T08:15:00Z',
  },
  {
    id: 'aud-007',
    userId: 'usr-001',
    action: 'Changement de statut',
    entity: 'ClinicalCase',
    entityId: 'cas-003',
    details: 'Statut modifié de "active" à "resolved" - Appendicite aiguë',
    ipAddress: '192.168.1.10',
    timestamp: '2026-06-22T10:00:00Z',
  },
  {
    id: 'aud-008',
    userId: 'usr-005',
    action: 'Export de données',
    entity: 'ClinicalCase',
    entityId: 'cas-017',
    details: 'Export du rapport du cas Cancer du sein en PDF',
    ipAddress: '192.168.1.40',
    timestamp: '2026-07-09T14:00:00Z',
  },
  {
    id: 'aud-009',
    userId: 'usr-004',
    action: 'Modification paramètres',
    entity: 'Facility',
    entityId: 'fac-001',
    details: 'Mise à jour des informations du CHU Mustapha',
    ipAddress: '192.168.1.5',
    timestamp: '2026-07-05T09:00:00Z',
  },
  {
    id: 'aud-010',
    userId: 'usr-008',
    action: 'Ajout pièce jointe',
    entity: 'ClinicalCase',
    entityId: 'cas-001',
    details: 'Ajout du scanner du fémur gauche en pièce jointe',
    ipAddress: '192.168.1.22',
    timestamp: '2026-07-02T14:30:00Z',
  },
  {
    id: 'aud-011',
    userId: 'usr-001',
    action: 'Consultation dossier',
    entity: 'Patient',
    entityId: 'pat-009',
    details: 'Consultation du dossier médical de Dalila Mansouri',
    ipAddress: '192.168.1.10',
    timestamp: '2026-07-11T09:45:00Z',
  },
  {
    id: 'aud-012',
    userId: 'usr-007',
    action: 'Modification traitement',
    entity: 'ClinicalCase',
    entityId: 'cas-010',
    details: 'Ajustement de la posologie de Furosémide pour le cas Insuffisance cardiaque',
    ipAddress: '192.168.1.35',
    timestamp: '2026-07-11T07:15:00Z',
  },
  {
    id: 'aud-013',
    userId: 'usr-006',
    action: 'Connexion',
    entity: 'User',
    entityId: 'usr-006',
    details: 'Connexion à la plateforme MedInsight',
    ipAddress: '192.168.1.50',
    timestamp: '2026-07-08T10:30:00Z',
  },
  {
    id: 'aud-014',
    userId: 'usr-002',
    action: 'Création cas clinique',
    entity: 'ClinicalCase',
    entityId: 'cas-016',
    details: 'Création du cas clinique "Dépression majeure récurrente"',
    ipAddress: '192.168.1.15',
    timestamp: '2026-07-08T10:00:00Z',
  },
  {
    id: 'aud-015',
    userId: 'usr-004',
    action: 'Gestion utilisateur',
    entity: 'User',
    entityId: 'usr-008',
    details: 'Activation du compte de Dr. Amine Slimani',
    ipAddress: '192.168.1.5',
    timestamp: '2026-07-07T14:00:00Z',
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'Nouveau cas clinique assigné',
    message: 'Le cas "Fracture du fémur gauche" vous a été assigné.',
    type: 'info',
    read: false,
    createdAt: '2026-07-11T08:30:00Z',
    link: '/cases/cas-001',
  },
  {
    id: 'notif-002',
    title: 'Synchronisation échouée',
    message: 'La synchronisation du cas "Polytraumatisme routier" a échoué. Veuillez réessayer.',
    type: 'error',
    read: false,
    createdAt: '2026-07-11T01:05:00Z',
    link: '/sync',
  },
  {
    id: 'notif-003',
    title: 'Cas résolu',
    message: 'Le cas "Appendicite aiguë" a été marqué comme résolu.',
    type: 'success',
    read: true,
    createdAt: '2026-06-22T10:00:00Z',
    link: '/cases/cas-003',
  },
  {
    id: 'notif-004',
    title: 'Rappel de suivi',
    message: 'Le patient Rachid Mebarki a un rendez-vous de suivi demain à 14h00.',
    type: 'warning',
    read: false,
    createdAt: '2026-07-11T09:00:00Z',
  },
  {
    id: 'notif-005',
    title: 'Mise à jour système',
    message: 'MedInsight sera mis à jour ce soir entre 22h et 23h.',
    type: 'info',
    read: true,
    createdAt: '2026-07-10T16:00:00Z',
  },
  {
    id: 'notif-006',
    title: 'Patient critique',
    message: 'Le patient Djamel Kharchi nécessite une attention immédiate (AVC ischémique).',
    type: 'error',
    read: false,
    createdAt: '2026-07-08T14:30:00Z',
    link: '/cases/cas-007',
  },
  {
    id: 'notif-007',
    title: 'Document prêt',
    message: 'Le rapport d\'analyse du cas "Cancer du sein" est prêt au téléchargement.',
    type: 'success',
    read: true,
    createdAt: '2026-07-09T14:30:00Z',
    link: '/cases/cas-017',
  },
  {
    id: 'notif-008',
    title: 'Connexion suspecte',
    message: 'Une connexion inhabituelle a été détectée sur votre compte depuis une adresse IP inconnue.',
    type: 'warning',
    read: false,
    createdAt: '2026-07-11T03:00:00Z',
  },
  {
    id: 'notif-009',
    title: 'Cas en attente de validation',
    message: '3 cas cliniques sont en attente de votre validation.',
    type: 'info',
    read: false,
    createdAt: '2026-07-11T07:00:00Z',
    link: '/cases?status=in_review',
  },
  {
    id: 'notif-010',
    title: 'Erreur de synchronisation',
    message: 'Conflit de version détecté pour le cas "Crisis hypertensive". Résolution manuelle requise.',
    type: 'error',
    read: true,
    createdAt: '2026-07-11T10:35:00Z',
    link: '/sync',
  },
]

export const mockChartData = {
  casesByMonth: [
    { name: 'Jan', value: 18 },
    { name: 'Fév', value: 22 },
    { name: 'Mar', value: 15 },
    { name: 'Avr', value: 28 },
    { name: 'Mai', value: 32 },
    { name: 'Juin', value: 25 },
    { name: 'Juil', value: 35 },
    { name: 'Août', value: 12 },
    { name: 'Sep', value: 20 },
    { name: 'Oct', value: 27 },
    { name: 'Nov', value: 30 },
    { name: 'Déc', value: 16 },
  ] satisfies ChartDataPoint[],

  casesByStatus: [
    { name: 'Brouillon', value: 3 },
    { name: 'Actif', value: 8 },
    { name: 'En revue', value: 4 },
    { name: 'Résolu', value: 3 },
    { name: 'Archivé', value: 2 },
  ] satisfies ChartDataPoint[],

  casesByFacility: [
    { name: 'CHU Mustapha', value: 8 },
    { name: 'Hôpital Bab El Oued', value: 5 },
    { name: 'Clinique El Fath', value: 4 },
    { name: 'Hôpital Parnet', value: 2 },
    { name: 'Centre Médical Hydra', value: 3 },
  ] satisfies ChartDataPoint[],

  treatmentOutcomes: [
    { name: 'Succès', value: 12 },
    { name: 'Échec', value: 2 },
    { name: 'En cours', value: 5 },
  ] satisfies ChartDataPoint[],
}
